//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collectio.Resources.Culture {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Collectio.Resources.Culture.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Collections {
            get {
                return ResourceManager.GetString("Collections", resourceCulture);
            }
        }
        
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        internal static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static string NoItems {
            get {
                return ResourceManager.GetString("NoItems", resourceCulture);
            }
        }
        
        internal static string NoCollections {
            get {
                return ResourceManager.GetString("NoCollections", resourceCulture);
            }
        }
        
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        internal static string NewCollection {
            get {
                return ResourceManager.GetString("NewCollection", resourceCulture);
            }
        }
        
        internal static string EmptyCollectionName {
            get {
                return ResourceManager.GetString("EmptyCollectionName", resourceCulture);
            }
        }
        
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        internal static string LoginGoogle {
            get {
                return ResourceManager.GetString("LoginGoogle", resourceCulture);
            }
        }
        
        internal static string LoginApple {
            get {
                return ResourceManager.GetString("LoginApple", resourceCulture);
            }
        }
        
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        internal static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        internal static string NoGroups {
            get {
                return ResourceManager.GetString("NoGroups", resourceCulture);
            }
        }
        
        internal static string EditCollection {
            get {
                return ResourceManager.GetString("EditCollection", resourceCulture);
            }
        }
        
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        internal static string CollectionsCount {
            get {
                return ResourceManager.GetString("CollectionsCount", resourceCulture);
            }
        }
        
        internal static string NewItem {
            get {
                return ResourceManager.GetString("NewItem", resourceCulture);
            }
        }
        
        internal static string Camera {
            get {
                return ResourceManager.GetString("Camera", resourceCulture);
            }
        }
        
        internal static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        internal static string SureQuestion {
            get {
                return ResourceManager.GetString("SureQuestion", resourceCulture);
            }
        }
        
        internal static string EditItem {
            get {
                return ResourceManager.GetString("EditItem", resourceCulture);
            }
        }
        
        internal static string DeleteCollection {
            get {
                return ResourceManager.GetString("DeleteCollection", resourceCulture);
            }
        }
        
        internal static string DeleteItem {
            get {
                return ResourceManager.GetString("DeleteItem", resourceCulture);
            }
        }
        
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        internal static string Duplicate {
            get {
                return ResourceManager.GetString("Duplicate", resourceCulture);
            }
        }
        
        internal static string DuplicateMessage {
            get {
                return ResourceManager.GetString("DuplicateMessage", resourceCulture);
            }
        }
        
        internal static string Subcategory {
            get {
                return ResourceManager.GetString("Subcategory", resourceCulture);
            }
        }
        
        internal static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        internal static string BackupDescription {
            get {
                return ResourceManager.GetString("BackupDescription", resourceCulture);
            }
        }
        
        internal static string AppCenter {
            get {
                return ResourceManager.GetString("AppCenter", resourceCulture);
            }
        }
        
        internal static string AppCenterDescription {
            get {
                return ResourceManager.GetString("AppCenterDescription", resourceCulture);
            }
        }
        
        internal static string RestoreBackup {
            get {
                return ResourceManager.GetString("RestoreBackup", resourceCulture);
            }
        }
        
        internal static string RestoreBackupDescription {
            get {
                return ResourceManager.GetString("RestoreBackupDescription", resourceCulture);
            }
        }
        
        internal static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        internal static string CommentsDescription {
            get {
                return ResourceManager.GetString("CommentsDescription", resourceCulture);
            }
        }
        
        internal static string EmptyItemName {
            get {
                return ResourceManager.GetString("EmptyItemName", resourceCulture);
            }
        }
        
        internal static string BackupError {
            get {
                return ResourceManager.GetString("BackupError", resourceCulture);
            }
        }
        
        internal static string BackupCorrect {
            get {
                return ResourceManager.GetString("BackupCorrect", resourceCulture);
            }
        }
        
        internal static string RestoreBackupError {
            get {
                return ResourceManager.GetString("RestoreBackupError", resourceCulture);
            }
        }
        
        internal static string RestoreBackupCorrect {
            get {
                return ResourceManager.GetString("RestoreBackupCorrect", resourceCulture);
            }
        }
        
        internal static string DeleteData {
            get {
                return ResourceManager.GetString("DeleteData", resourceCulture);
            }
        }
        
        internal static string DeleteDataDescription {
            get {
                return ResourceManager.GetString("DeleteDataDescription", resourceCulture);
            }
        }
        
        internal static string DeleteCache {
            get {
                return ResourceManager.GetString("DeleteCache", resourceCulture);
            }
        }
        
        internal static string DeleteCacheDescription {
            get {
                return ResourceManager.GetString("DeleteCacheDescription", resourceCulture);
            }
        }
        
        internal static string DeleteDataCorrect {
            get {
                return ResourceManager.GetString("DeleteDataCorrect", resourceCulture);
            }
        }
        
        internal static string DeleteCacheCorrect {
            get {
                return ResourceManager.GetString("DeleteCacheCorrect", resourceCulture);
            }
        }
        
        internal static string DeleteDataError {
            get {
                return ResourceManager.GetString("DeleteDataError", resourceCulture);
            }
        }
        
        internal static string DeleteCacheError {
            get {
                return ResourceManager.GetString("DeleteCacheError", resourceCulture);
            }
        }
        
        internal static string DisabledFunction {
            get {
                return ResourceManager.GetString("DisabledFunction", resourceCulture);
            }
        }
        
        internal static string ImageOrigin {
            get {
                return ResourceManager.GetString("ImageOrigin", resourceCulture);
            }
        }
        
        internal static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        internal static string CollectionSearch {
            get {
                return ResourceManager.GetString("CollectionSearch", resourceCulture);
            }
        }
        
        internal static string ItemSearch {
            get {
                return ResourceManager.GetString("ItemSearch", resourceCulture);
            }
        }
        
        internal static string LoginBenefit {
            get {
                return ResourceManager.GetString("LoginBenefit", resourceCulture);
            }
        }
        
        internal static string Mail {
            get {
                return ResourceManager.GetString("Mail", resourceCulture);
            }
        }
        
        internal static string Nickname {
            get {
                return ResourceManager.GetString("Nickname", resourceCulture);
            }
        }
        
        internal static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        internal static string CommentAddition {
            get {
                return ResourceManager.GetString("CommentAddition", resourceCulture);
            }
        }
        
        internal static string CommentBugReport {
            get {
                return ResourceManager.GetString("CommentBugReport", resourceCulture);
            }
        }
        
        internal static string CommentExplain {
            get {
                return ResourceManager.GetString("CommentExplain", resourceCulture);
            }
        }
        
        internal static string CommentNotComplete {
            get {
                return ResourceManager.GetString("CommentNotComplete", resourceCulture);
            }
        }
        
        internal static string CategoryNotSelected {
            get {
                return ResourceManager.GetString("CategoryNotSelected", resourceCulture);
            }
        }
    }
}
